# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v17.0.3'
  hooks:
  - id: clang-format
    types_or:
      - "c"
      - "c++"
      - "json"

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format

- repo: https://github.com/crate-ci/typos
  rev: v1.16.21
  hooks:
    - id: typos
